// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oawfadvghcomvnvxkjqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hd2ZhZHZnaGNvbXZudnhranF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NzcyODgsImV4cCI6MjA1MTA1MzI4OH0.M9QDuOvel_IAaFEkm7_AIFT3UVWyFOtwg99ofxkmChI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);